//
// FleetAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class FleetAPI {
    /**
     Create a vehicle.    Requires the 'ManageFleet' permission.
     
     - parameter request: (body) An Insert Vehicle Request object containing values for the new Vehicle to create 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func fleetCreateVehicle(request: CSInsertVehicleRequest, xChronosheetsAuth: String, completion: @escaping ((_ data: CSApiResponseInt32?,_ error: Error?) -> Void)) {
        fleetCreateVehicleWithRequestBuilder(request: request, xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Create a vehicle.    Requires the 'ManageFleet' permission.
     - POST /Fleet/CreateVehicle
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : 0
}}, {contentType=application/xml, example=<null>
  <Data>123</Data>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : 0
}}, {contentType=application/xml, example=<null>
  <Data>123</Data>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     
     - parameter request: (body) An Insert Vehicle Request object containing values for the new Vehicle to create 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 

     - returns: RequestBuilder<CSApiResponseInt32> 
     */
    open class func fleetCreateVehicleWithRequestBuilder(request: CSInsertVehicleRequest, xChronosheetsAuth: String) -> RequestBuilder<CSApiResponseInt32> {
        let path = "/Fleet/CreateVehicle"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: request)

        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CSApiResponseInt32>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

    /**
     Delete a vehicle from the fleet.  Requires the 'ManageFleet' permission.
     
     - parameter vehicleId: (query) The unique ID of the vehicle you wish to delete 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func fleetDeleteVehicle(vehicleId: Int, xChronosheetsAuth: String, completion: @escaping ((_ data: CSApiResponseBoolean?,_ error: Error?) -> Void)) {
        fleetDeleteVehicleWithRequestBuilder(vehicleId: vehicleId, xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Delete a vehicle from the fleet.  Requires the 'ManageFleet' permission.
     - DELETE /Fleet/DeleteVehicle
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : true
}}, {contentType=application/xml, example=<null>
  <Data>true</Data>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : true
}}, {contentType=application/xml, example=<null>
  <Data>true</Data>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     
     - parameter vehicleId: (query) The unique ID of the vehicle you wish to delete 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 

     - returns: RequestBuilder<CSApiResponseBoolean> 
     */
    open class func fleetDeleteVehicleWithRequestBuilder(vehicleId: Int, xChronosheetsAuth: String) -> RequestBuilder<CSApiResponseBoolean> {
        let path = "/Fleet/DeleteVehicle"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "VehicleId": vehicleId.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CSApiResponseBoolean>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Get a particular vehicle.  Does not require any special permission.
     
     - parameter vehicleId: (query) The ID of the Vehicle you want to get 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func fleetGetVehicleById(vehicleId: Int, xChronosheetsAuth: String, completion: @escaping ((_ data: CSApiResponseFleetVehicle?,_ error: Error?) -> Void)) {
        fleetGetVehicleByIdWithRequestBuilder(vehicleId: vehicleId, xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a particular vehicle.  Does not require any special permission.
     - GET /Fleet/GetVehicleById
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : {
    "IsDeleted" : true,
    "Year" : "Year",
    "PermittedEmployees" : [ 5, 5 ],
    "OrganisationId" : 6,
    "Model" : "Model",
    "Make" : "Make",
    "Id" : 0,
    "CostPerKilometer" : 1.4658129805029452,
    "LicencePlateNumber" : "LicencePlateNumber",
    "Name" : "Name"
  }
}}, {contentType=application/xml, example=<null>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : {
    "IsDeleted" : true,
    "Year" : "Year",
    "PermittedEmployees" : [ 5, 5 ],
    "OrganisationId" : 6,
    "Model" : "Model",
    "Make" : "Make",
    "Id" : 0,
    "CostPerKilometer" : 1.4658129805029452,
    "LicencePlateNumber" : "LicencePlateNumber",
    "Name" : "Name"
  }
}}, {contentType=application/xml, example=<null>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     
     - parameter vehicleId: (query) The ID of the Vehicle you want to get 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 

     - returns: RequestBuilder<CSApiResponseFleetVehicle> 
     */
    open class func fleetGetVehicleByIdWithRequestBuilder(vehicleId: Int, xChronosheetsAuth: String) -> RequestBuilder<CSApiResponseFleetVehicle> {
        let path = "/Fleet/GetVehicleById"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "VehicleId": vehicleId.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CSApiResponseFleetVehicle>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Get a collection of vehicles that are under your organisation.    Does not require any special permission.
     
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter includeDeleted: (query) Whether or not to include deleted vehicles (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func fleetGetVehicles(xChronosheetsAuth: String, includeDeleted: Bool? = nil, completion: @escaping ((_ data: CSApiResponseListFleetVehicle?,_ error: Error?) -> Void)) {
        fleetGetVehiclesWithRequestBuilder(xChronosheetsAuth: xChronosheetsAuth, includeDeleted: includeDeleted).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get a collection of vehicles that are under your organisation.    Does not require any special permission.
     - GET /Fleet/GetVehicles
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : [ {
    "IsDeleted" : true,
    "Year" : "Year",
    "PermittedEmployees" : [ 5, 5 ],
    "OrganisationId" : 6,
    "Model" : "Model",
    "Make" : "Make",
    "Id" : 0,
    "CostPerKilometer" : 1.4658129805029452,
    "LicencePlateNumber" : "LicencePlateNumber",
    "Name" : "Name"
  }, {
    "IsDeleted" : true,
    "Year" : "Year",
    "PermittedEmployees" : [ 5, 5 ],
    "OrganisationId" : 6,
    "Model" : "Model",
    "Make" : "Make",
    "Id" : 0,
    "CostPerKilometer" : 1.4658129805029452,
    "LicencePlateNumber" : "LicencePlateNumber",
    "Name" : "Name"
  } ]
}}, {contentType=application/xml, example=<null>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : [ {
    "IsDeleted" : true,
    "Year" : "Year",
    "PermittedEmployees" : [ 5, 5 ],
    "OrganisationId" : 6,
    "Model" : "Model",
    "Make" : "Make",
    "Id" : 0,
    "CostPerKilometer" : 1.4658129805029452,
    "LicencePlateNumber" : "LicencePlateNumber",
    "Name" : "Name"
  }, {
    "IsDeleted" : true,
    "Year" : "Year",
    "PermittedEmployees" : [ 5, 5 ],
    "OrganisationId" : 6,
    "Model" : "Model",
    "Make" : "Make",
    "Id" : 0,
    "CostPerKilometer" : 1.4658129805029452,
    "LicencePlateNumber" : "LicencePlateNumber",
    "Name" : "Name"
  } ]
}}, {contentType=application/xml, example=<null>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter includeDeleted: (query) Whether or not to include deleted vehicles (optional)

     - returns: RequestBuilder<CSApiResponseListFleetVehicle> 
     */
    open class func fleetGetVehiclesWithRequestBuilder(xChronosheetsAuth: String, includeDeleted: Bool? = nil) -> RequestBuilder<CSApiResponseListFleetVehicle> {
        let path = "/Fleet/GetVehicles"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "IncludeDeleted": includeDeleted
        ])
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CSApiResponseListFleetVehicle>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Update a vehicle.    Requires the 'ManageFleet' permission.
     
     - parameter request: (body) A Save Vehicle Request object containing updated fields.  Make sure to specify the Vehicle Id in the request object so that ChronoSheets knows which Vehicle to update 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func fleetUpdateVehicle(request: CSSaveVehicleRequest, xChronosheetsAuth: String, completion: @escaping ((_ data: CSApiResponseBoolean?,_ error: Error?) -> Void)) {
        fleetUpdateVehicleWithRequestBuilder(request: request, xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update a vehicle.    Requires the 'ManageFleet' permission.
     - PUT /Fleet/UpdateVehicle
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : true
}}, {contentType=application/xml, example=<null>
  <Data>true</Data>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     - examples: [{contentType=application/json, example={
  "Status" : "Succeeded",
  "Message" : "Message",
  "Data" : true
}}, {contentType=application/xml, example=<null>
  <Data>true</Data>
  <Status>aeiou</Status>
  <Message>aeiou</Message>
</null>}]
     
     - parameter request: (body) A Save Vehicle Request object containing updated fields.  Make sure to specify the Vehicle Id in the request object so that ChronoSheets knows which Vehicle to update 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 

     - returns: RequestBuilder<CSApiResponseBoolean> 
     */
    open class func fleetUpdateVehicleWithRequestBuilder(request: CSSaveVehicleRequest, xChronosheetsAuth: String) -> RequestBuilder<CSApiResponseBoolean> {
        let path = "/Fleet/UpdateVehicle"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: request)

        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CSApiResponseBoolean>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

}
