//
// CsApiProjectTotalsReportItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CsApiProjectTotalsReportItem: Codable {

    public var organisationId: Int?
    public var userId: Int?
    public var projectId: Int?
    public var projectName: String?
    public var spanSeconds: Int?


    
    public init(organisationId: Int?, userId: Int?, projectId: Int?, projectName: String?, spanSeconds: Int?) {
        self.organisationId = organisationId
        self.userId = userId
        self.projectId = projectId
        self.projectName = projectName
        self.spanSeconds = spanSeconds
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(organisationId, forKey: "OrganisationId")
        try container.encodeIfPresent(userId, forKey: "UserId")
        try container.encodeIfPresent(projectId, forKey: "ProjectId")
        try container.encodeIfPresent(projectName, forKey: "ProjectName")
        try container.encodeIfPresent(spanSeconds, forKey: "SpanSeconds")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        organisationId = try container.decodeIfPresent(Int.self, forKey: "OrganisationId")
        userId = try container.decodeIfPresent(Int.self, forKey: "UserId")
        projectId = try container.decodeIfPresent(Int.self, forKey: "ProjectId")
        projectName = try container.decodeIfPresent(String.self, forKey: "ProjectName")
        spanSeconds = try container.decodeIfPresent(Int.self, forKey: "SpanSeconds")
    }
}

