//
// CsApiUpdateTaskRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CsApiUpdateTaskRequest: Codable {

    public var id: Int?
    public var taskName: String?
    public var isDeleted: Bool?
    public var tripEnabled: Bool?


    
    public init(id: Int?, taskName: String?, isDeleted: Bool?, tripEnabled: Bool?) {
        self.id = id
        self.taskName = taskName
        self.isDeleted = isDeleted
        self.tripEnabled = tripEnabled
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(taskName, forKey: "TaskName")
        try container.encodeIfPresent(isDeleted, forKey: "IsDeleted")
        try container.encodeIfPresent(tripEnabled, forKey: "TripEnabled")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        taskName = try container.decodeIfPresent(String.self, forKey: "TaskName")
        isDeleted = try container.decodeIfPresent(Bool.self, forKey: "IsDeleted")
        tripEnabled = try container.decodeIfPresent(Bool.self, forKey: "TripEnabled")
    }
}

