//
// CsApiJobSeriesReportItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CsApiJobSeriesReportItem: Codable {

    public var startDate: Date?
    public var endDate: Date?
    public var jobId: Int?
    public var clientId: Int?
    public var clientName: String?
    public var projectId: Int?
    public var projectName: String?
    public var spanSeconds: Int?
    public var jobCode: String?


    
    public init(startDate: Date?, endDate: Date?, jobId: Int?, clientId: Int?, clientName: String?, projectId: Int?, projectName: String?, spanSeconds: Int?, jobCode: String?) {
        self.startDate = startDate
        self.endDate = endDate
        self.jobId = jobId
        self.clientId = clientId
        self.clientName = clientName
        self.projectId = projectId
        self.projectName = projectName
        self.spanSeconds = spanSeconds
        self.jobCode = jobCode
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(startDate, forKey: "StartDate")
        try container.encodeIfPresent(endDate, forKey: "EndDate")
        try container.encodeIfPresent(jobId, forKey: "JobId")
        try container.encodeIfPresent(clientId, forKey: "ClientId")
        try container.encodeIfPresent(clientName, forKey: "ClientName")
        try container.encodeIfPresent(projectId, forKey: "ProjectId")
        try container.encodeIfPresent(projectName, forKey: "ProjectName")
        try container.encodeIfPresent(spanSeconds, forKey: "SpanSeconds")
        try container.encodeIfPresent(jobCode, forKey: "JobCode")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        startDate = try container.decodeIfPresent(Date.self, forKey: "StartDate")
        endDate = try container.decodeIfPresent(Date.self, forKey: "EndDate")
        jobId = try container.decodeIfPresent(Int.self, forKey: "JobId")
        clientId = try container.decodeIfPresent(Int.self, forKey: "ClientId")
        clientName = try container.decodeIfPresent(String.self, forKey: "ClientName")
        projectId = try container.decodeIfPresent(Int.self, forKey: "ProjectId")
        projectName = try container.decodeIfPresent(String.self, forKey: "ProjectName")
        spanSeconds = try container.decodeIfPresent(Int.self, forKey: "SpanSeconds")
        jobCode = try container.decodeIfPresent(String.self, forKey: "JobCode")
    }
}

