//
// CSInsertUserJobFavouriteRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CSInsertUserJobFavouriteRequest: Codable {

    public var jobId: Int?


    
    public init(jobId: Int?) {
        self.jobId = jobId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(jobId, forKey: "JobId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        jobId = try container.decodeIfPresent(Int.self, forKey: "JobId")
    }
}

