//
// UsualHoursAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class UsualHoursAPI {
    /**
     Get usual hours (rostered hours) for an employee
     
     - parameter userId: (query)  
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usualHoursGetUsualHours(userId: Int, xChronosheetsAuth: String, completion: @escaping ((_ data: CsApiApiResponseListUsualHoursDay?,_ error: Error?) -> Void)) {
        usualHoursGetUsualHoursWithRequestBuilder(userId: userId, xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Get usual hours (rostered hours) for an employee
     - GET /api/UsualHours/GetUsualHours
     - examples: [{contentType=application/json, example={
  "Status" : 3,
  "Message" : "Message",
  "Data" : [ {
    "DeleteUsualHours" : [ 9, 9 ],
    "DayType" : 0,
    "TimeSlots" : [ {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    }, {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    } ]
  }, {
    "DeleteUsualHours" : [ 9, 9 ],
    "DayType" : 0,
    "TimeSlots" : [ {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    }, {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    } ]
  } ]
}}, {contentType=application/xml, example=<null>
  <Status>123</Status>
  <Message>aeiou</Message>
</null>}]
     - examples: [{contentType=application/json, example={
  "Status" : 3,
  "Message" : "Message",
  "Data" : [ {
    "DeleteUsualHours" : [ 9, 9 ],
    "DayType" : 0,
    "TimeSlots" : [ {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    }, {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    } ]
  }, {
    "DeleteUsualHours" : [ 9, 9 ],
    "DayType" : 0,
    "TimeSlots" : [ {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    }, {
      "StartMinute" : 5,
      "StartHour" : 5,
      "UsualHourId" : 1,
      "DayType" : 6,
      "EndHour" : 2,
      "EndMinute" : 7,
      "IsValid" : true
    } ]
  } ]
}}, {contentType=application/xml, example=<null>
  <Status>123</Status>
  <Message>aeiou</Message>
</null>}]
     
     - parameter userId: (query)  
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 

     - returns: RequestBuilder<CsApiApiResponseListUsualHoursDay> 
     */
    open class func usualHoursGetUsualHoursWithRequestBuilder(userId: Int, xChronosheetsAuth: String) -> RequestBuilder<CsApiApiResponseListUsualHoursDay> {
        let path = "/api/UsualHours/GetUsualHours"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "UserId": userId.encodeToJSON()
        ])
        
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CsApiApiResponseListUsualHoursDay>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Set usual hours (rostered hours) for an employee
     
     - parameter request: (body)  
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usualHoursSetUsualHours(request: CsApiSetUsualHoursRequest, xChronosheetsAuth: String, completion: @escaping ((_ data: CsApiApiResponseBoolean?,_ error: Error?) -> Void)) {
        usualHoursSetUsualHoursWithRequestBuilder(request: request, xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Set usual hours (rostered hours) for an employee
     - POST /api/UsualHours/SetUsualHours
     - examples: [{contentType=application/json, example={
  "Status" : 0,
  "Message" : "Message",
  "Data" : true
}}, {contentType=application/xml, example=<null>
  <Data>true</Data>
  <Status>123</Status>
  <Message>aeiou</Message>
</null>}]
     - examples: [{contentType=application/json, example={
  "Status" : 0,
  "Message" : "Message",
  "Data" : true
}}, {contentType=application/xml, example=<null>
  <Data>true</Data>
  <Status>123</Status>
  <Message>aeiou</Message>
</null>}]
     
     - parameter request: (body)  
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 

     - returns: RequestBuilder<CsApiApiResponseBoolean> 
     */
    open class func usualHoursSetUsualHoursWithRequestBuilder(request: CsApiSetUsualHoursRequest, xChronosheetsAuth: String) -> RequestBuilder<CsApiApiResponseBoolean> {
        let path = "/api/UsualHours/SetUsualHours"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: request)

        let url = NSURLComponents(string: URLString)

        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<CsApiApiResponseBoolean>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

}
