//
// UserJobFavouritesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class UserJobFavouritesAPI {
    /**
     Create a job favourite.    Requires the 'SubmitTimesheets' permission.
     
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter request: (body) An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userJobFavouritesCreateJobFavourite(xChronosheetsAuth: String, request: InsertUserJobFavouriteRequest, completion: @escaping ((_ data: ApiResponseInt32?,_ error: Error?) -> Void)) {
        userJobFavouritesCreateJobFavouriteWithRequestBuilder(xChronosheetsAuth: xChronosheetsAuth, request: request).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Create a job favourite.    Requires the 'SubmitTimesheets' permission.
     - POST /UserJobFavourites/CreateJobFavourite
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter request: (body) An Insert UserJobFavourite Request object containing values for the new UserJobFavourite to create 
     - returns: RequestBuilder<ApiResponseInt32> 
     */
    open class func userJobFavouritesCreateJobFavouriteWithRequestBuilder(xChronosheetsAuth: String, request: InsertUserJobFavouriteRequest) -> RequestBuilder<ApiResponseInt32> {
        let path = "/UserJobFavourites/CreateJobFavourite"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: request)

        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ApiResponseInt32>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true, headers: headerParameters)
    }

    /**
     Delete a job favourite.    Requires the 'SubmitTimesheets' permission.
     
     - parameter jobId: (query) The ID of the Job for the Job Favourite you want to delete. 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userJobFavouritesDeleteJobFavourite(jobId: Int, xChronosheetsAuth: String, completion: @escaping ((_ data: ApiResponseBoolean?,_ error: Error?) -> Void)) {
        userJobFavouritesDeleteJobFavouriteWithRequestBuilder(jobId: jobId, xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Delete a job favourite.    Requires the 'SubmitTimesheets' permission.
     - DELETE /UserJobFavourites/DeleteJobFavourite
     - parameter jobId: (query) The ID of the Job for the Job Favourite you want to delete. 
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - returns: RequestBuilder<ApiResponseBoolean> 
     */
    open class func userJobFavouritesDeleteJobFavouriteWithRequestBuilder(jobId: Int, xChronosheetsAuth: String) -> RequestBuilder<ApiResponseBoolean> {
        let path = "/UserJobFavourites/DeleteJobFavourite"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "JobId": jobId.encodeToJSON()
        ])
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ApiResponseBoolean>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

    /**
     Get your job favourites.    Requires the 'SubmitTimesheets' permission.
     
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userJobFavouritesGetJobFavourites(xChronosheetsAuth: String, completion: @escaping ((_ data: ApiResponseListUserJobFavourite?,_ error: Error?) -> Void)) {
        userJobFavouritesGetJobFavouritesWithRequestBuilder(xChronosheetsAuth: xChronosheetsAuth).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Get your job favourites.    Requires the 'SubmitTimesheets' permission.
     - GET /UserJobFavourites/GetJobFavourites
     - parameter xChronosheetsAuth: (header) The ChronoSheets Auth Token 
     - returns: RequestBuilder<ApiResponseListUserJobFavourite> 
     */
    open class func userJobFavouritesGetJobFavouritesWithRequestBuilder(xChronosheetsAuth: String) -> RequestBuilder<ApiResponseListUserJobFavourite> {
        let path = "/UserJobFavourites/GetJobFavourites"
        let URLString = ChronoSheetsAPIAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)
        let nillableHeaders: [String: Any?] = [
            "x-chronosheets-auth": xChronosheetsAuth.encodeToJSON()
        ]
        let headerParameters = APIHelper.rejectNilHeaders(nillableHeaders)

        let requestBuilder: RequestBuilder<ApiResponseListUserJobFavourite>.Type = ChronoSheetsAPIAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false, headers: headerParameters)
    }

}
