//
// CSAggregateJobTask.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CSAggregateJobTask: Codable {

    /** The Id of the task */
    public var _id: Int?
    /** The label of the task */
    public var label: String?
    /** A flag indicating that this task has been marked as deleted */
    public var isDeleted: Bool?

    public init(_id: Int?, label: String?, isDeleted: Bool?) {
        self._id = _id
        self.label = label
        self.isDeleted = isDeleted
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "Id"
        case label = "Label"
        case isDeleted = "IsDeleted"
    }


}

