//
// CSCreateTripRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Contains fields for creating a Trip */

open class CSCreateTripRequest: Codable {

    public enum CSMobilePlatform: String, Codable { 
        case unknown = "Unknown"
        case ios = "iOS"
        case android = "Android"
    }
    /** The associated Timesheet record Id.  The Trip will be linked to the Timesheet with this TimesheetId */
    public var timesheetId: Int?
    /** The associated Vehicle Id.  The Trip will show that this Vehicle was used */
    public var vehicleId: Int?
    /** A CSV of GPS path co-ordinates.  Format example: -37.8433562,144.7226188;[Lat1],[Long1];........[LatN],[LongN] */
    public var pathCoordsStringCsv: String?
    /** The total distance of the Trip */
    public var distanceMeters: Double?
    /** The Mobile platform that the Trip was recorded on */
    public var mobilePlatform: CSMobilePlatform?


    
    public init(timesheetId: Int?, vehicleId: Int?, pathCoordsStringCsv: String?, distanceMeters: Double?, mobilePlatform: CSMobilePlatform?) {
        self.timesheetId = timesheetId
        self.vehicleId = vehicleId
        self.pathCoordsStringCsv = pathCoordsStringCsv
        self.distanceMeters = distanceMeters
        self.mobilePlatform = mobilePlatform
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(timesheetId, forKey: "TimesheetId")
        try container.encodeIfPresent(vehicleId, forKey: "VehicleId")
        try container.encodeIfPresent(pathCoordsStringCsv, forKey: "PathCoordsStringCsv")
        try container.encodeIfPresent(distanceMeters, forKey: "DistanceMeters")
        try container.encodeIfPresent(mobilePlatform, forKey: "MobilePlatform")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        timesheetId = try container.decodeIfPresent(Int.self, forKey: "TimesheetId")
        vehicleId = try container.decodeIfPresent(Int.self, forKey: "VehicleId")
        pathCoordsStringCsv = try container.decodeIfPresent(String.self, forKey: "PathCoordsStringCsv")
        distanceMeters = try container.decodeIfPresent(Double.self, forKey: "DistanceMeters")
        mobilePlatform = try container.decodeIfPresent(CSMobilePlatform.self, forKey: "MobilePlatform")
    }
}

