//
// CSDoLoginResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** A Response object containing important information that can be used after the user has logged in */

public struct CSDoLoginResponse: Codable {

    /** The ChronoSheets Auth Token.  Use this token for all subsequent requests to the API.  The Auth Token does these things: holds your session and gives you appropraite authorisation to access API endpoints based on your UserRoles */
    public var cSAuthToken: String?
    /** An object containg all your account information */
    public var loggedInUser: CSClientSideUser?

    public init(cSAuthToken: String?, loggedInUser: CSClientSideUser?) {
        self.cSAuthToken = cSAuthToken
        self.loggedInUser = loggedInUser
    }

    public enum CodingKeys: String, CodingKey { 
        case cSAuthToken = "CSAuthToken"
        case loggedInUser = "LoggedInUser"
    }


}

