//
// CSInsertOrganisationGroupRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Fields for inserting a new Organisation Group */

public struct CSInsertOrganisationGroupRequest: Codable {

    /** The name of the new Organisation Group.  This is used when you&#39;re looking up Organisation Groups elsewhere through ChronoSheets */
    public var organisationGroupName: String?
    /** The Ids of the Users that are going to be in this Organisation Group */
    public var organisationGroupUserIds: [Int]?

    public init(organisationGroupName: String?, organisationGroupUserIds: [Int]?) {
        self.organisationGroupName = organisationGroupName
        self.organisationGroupUserIds = organisationGroupUserIds
    }

    public enum CodingKeys: String, CodingKey { 
        case organisationGroupName = "OrganisationGroupName"
        case organisationGroupUserIds = "OrganisationGroupUserIds"
    }


}

