//
// CSJobSeriesReportItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CSJobSeriesReportItem: Codable {

    public var startDate: Date?
    public var endDate: Date?
    public var jobId: Int?
    public var clientId: Int?
    public var clientName: String?
    public var projectId: Int?
    public var projectName: String?
    public var spanSeconds: Int?
    public var jobCode: String?

    public init(startDate: Date?, endDate: Date?, jobId: Int?, clientId: Int?, clientName: String?, projectId: Int?, projectName: String?, spanSeconds: Int?, jobCode: String?) {
        self.startDate = startDate
        self.endDate = endDate
        self.jobId = jobId
        self.clientId = clientId
        self.clientName = clientName
        self.projectId = projectId
        self.projectName = projectName
        self.spanSeconds = spanSeconds
        self.jobCode = jobCode
    }

    public enum CodingKeys: String, CodingKey { 
        case startDate = "StartDate"
        case endDate = "EndDate"
        case jobId = "JobId"
        case clientId = "ClientId"
        case clientName = "ClientName"
        case projectId = "ProjectId"
        case projectName = "ProjectName"
        case spanSeconds = "SpanSeconds"
        case jobCode = "JobCode"
    }


}

