//
// CSTimeSlot.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CSTimeSlot: Codable {

    public enum CSDayType: String, Codable { 
        case monday = "Monday"
        case tuesday = "Tuesday"
        case wednesday = "Wednesday"
        case thursday = "Thursday"
        case friday = "Friday"
        case saturday = "Saturday"
        case sunday = "Sunday"
    }
    public var dayType: CSDayType?
    public var usualHourId: Int?
    public var startHour: Int?
    public var startMinute: Int?
    public var endHour: Int?
    public var endMinute: Int?
    public var isValid: Bool?

    public init(dayType: CSDayType?, usualHourId: Int?, startHour: Int?, startMinute: Int?, endHour: Int?, endMinute: Int?, isValid: Bool?) {
        self.dayType = dayType
        self.usualHourId = usualHourId
        self.startHour = startHour
        self.startMinute = startMinute
        self.endHour = endHour
        self.endMinute = endMinute
        self.isValid = isValid
    }

    public enum CodingKeys: String, CodingKey { 
        case dayType = "DayType"
        case usualHourId = "UsualHourId"
        case startHour = "StartHour"
        case startMinute = "StartMinute"
        case endHour = "EndHour"
        case endMinute = "EndMinute"
        case isValid = "IsValid"
    }


}

