//
// CSTripCoordinate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CSTripCoordinate: Codable {

    public var latitude: Double?
    public var longitude: Double?

    public init(latitude: Double?, longitude: Double?) {
        self.latitude = latitude
        self.longitude = longitude
    }

    public enum CodingKeys: String, CodingKey { 
        case latitude = "Latitude"
        case longitude = "Longitude"
    }


}

