//
// CSUpdateOrganisationResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CSUpdateOrganisationResponse: Codable {

    public var validationErrors: [String]?

    public init(validationErrors: [String]?) {
        self.validationErrors = validationErrors
    }

    public enum CodingKeys: String, CodingKey { 
        case validationErrors = "ValidationErrors"
    }


}

