//
// CSUpdateJobCodeRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Fields used to update an existing JobCode */

open class CSUpdateJobCodeRequest: Codable {

    /** The Id of the JobCode to be updated */
    public var id: Int?
    /** The new JobCode to be set */
    public var code: String?
    /** The Id of the Project to be associated to */
    public var projectId: Int?
    /** The Id of the Client to be associated to */
    public var clientId: Int?
    /** A collection of Task Ids to be available when choosing this JobCode */
    public var linkedTaskIds: [Int]?
    /** Restrict the access to this JobCode by specifying which Organisation Groups can have access.  Only employees in these Organisation Groups will be able to access this JobCode */
    public var linkedOrgGroupIds: [Int]?
    /** Whether or not this JobCode is to be marked as deleted */
    public var isDeleted: Bool?


    
    public init(id: Int?, code: String?, projectId: Int?, clientId: Int?, linkedTaskIds: [Int]?, linkedOrgGroupIds: [Int]?, isDeleted: Bool?) {
        self.id = id
        self.code = code
        self.projectId = projectId
        self.clientId = clientId
        self.linkedTaskIds = linkedTaskIds
        self.linkedOrgGroupIds = linkedOrgGroupIds
        self.isDeleted = isDeleted
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(id, forKey: "Id")
        try container.encodeIfPresent(code, forKey: "Code")
        try container.encodeIfPresent(projectId, forKey: "ProjectId")
        try container.encodeIfPresent(clientId, forKey: "ClientId")
        try container.encodeIfPresent(linkedTaskIds, forKey: "LinkedTaskIds")
        try container.encodeIfPresent(linkedOrgGroupIds, forKey: "LinkedOrgGroupIds")
        try container.encodeIfPresent(isDeleted, forKey: "IsDeleted")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        id = try container.decodeIfPresent(Int.self, forKey: "Id")
        code = try container.decodeIfPresent(String.self, forKey: "Code")
        projectId = try container.decodeIfPresent(Int.self, forKey: "ProjectId")
        clientId = try container.decodeIfPresent(Int.self, forKey: "ClientId")
        linkedTaskIds = try container.decodeIfPresent([Int].self, forKey: "LinkedTaskIds")
        linkedOrgGroupIds = try container.decodeIfPresent([Int].self, forKey: "LinkedOrgGroupIds")
        isDeleted = try container.decodeIfPresent(Bool.self, forKey: "IsDeleted")
    }
}

