//
// AggregateJobTask.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AggregateJobTask: Codable { 


    /** The Id of the task */
    public var id: Int?
    /** The label of the task */
    public var label: String?
    /** A flag indicating that this task has been marked as deleted */
    public var isDeleted: Bool?

    public init(id: Int?, label: String?, isDeleted: Bool?) {
        self.id = id
        self.label = label
        self.isDeleted = isDeleted
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "Id"
        case label = "Label"
        case isDeleted = "IsDeleted"
    }

}
