//
// BasicGeofence.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BasicGeofence: Codable { 


    public var geoFencingId: Int?
    public var name: String?

    public init(geoFencingId: Int?, name: String?) {
        self.geoFencingId = geoFencingId
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case geoFencingId = "GeoFencingId"
        case name = "Name"
    }

}
