//
// BatchUpdateTimesheetRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contains a collection of Timesheet objects that are to be either created or updated.  If the ID of the timesheet is specified in the Timesheet object, then that Timesheet will be updated otherwise it will be created */
public struct BatchUpdateTimesheetRequest: Codable { 


    /** A collection of Timesheet objects to be either created or updated */
    public var timesheets: [Timesheet]?

    public init(timesheets: [Timesheet]?) {
        self.timesheets = timesheets
    }

    public enum CodingKeys: String, CodingKey { 
        case timesheets = "Timesheets"
    }

}
