//
// CreateTripRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Contains fields for creating a Trip */
public struct CreateTripRequest: Codable { 


    public enum MobilePlatform: String, Codable {
        case unknown = "Unknown"
        case ios = "iOS"
        case android = "Android"
    }
    /** The associated Timesheet record Id.  The Trip will be linked to the Timesheet with this TimesheetId */
    public var timesheetId: Int?
    /** The associated Vehicle Id.  The Trip will show that this Vehicle was used */
    public var vehicleId: Int?
    /** A CSV of GPS path co-ordinates.  Format example: -37.8433562,144.7226188;[Lat1],[Long1];........[LatN],[LongN] */
    public var pathCoordsStringCsv: String?
    /** The total distance of the Trip */
    public var distanceMeters: Double?
    /** The Mobile platform that the Trip was recorded on */
    public var mobilePlatform: MobilePlatform?

    public init(timesheetId: Int?, vehicleId: Int?, pathCoordsStringCsv: String?, distanceMeters: Double?, mobilePlatform: MobilePlatform?) {
        self.timesheetId = timesheetId
        self.vehicleId = vehicleId
        self.pathCoordsStringCsv = pathCoordsStringCsv
        self.distanceMeters = distanceMeters
        self.mobilePlatform = mobilePlatform
    }

    public enum CodingKeys: String, CodingKey { 
        case timesheetId = "TimesheetId"
        case vehicleId = "VehicleId"
        case pathCoordsStringCsv = "PathCoordsStringCsv"
        case distanceMeters = "DistanceMeters"
        case mobilePlatform = "MobilePlatform"
    }

}
