//
// DoLoginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An API Request object for logging into ChronoSheets */
public struct DoLoginRequest: Codable { 


    /** Your ChronoSheets username or registered email address */
    public var usernameOrEmail: String?
    /** Your ChronoSheets password */
    public var password: String?
    /** Increase session expiry beyond default of 1 hour */
    public var rememberMe: Bool?

    public init(usernameOrEmail: String?, password: String?, rememberMe: Bool?) {
        self.usernameOrEmail = usernameOrEmail
        self.password = password
        self.rememberMe = rememberMe
    }

    public enum CodingKeys: String, CodingKey { 
        case usernameOrEmail = "UsernameOrEmail"
        case password = "Password"
        case rememberMe = "RememberMe"
    }

}
