//
// OrganisationPricingPlan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OrganisationPricingPlan: Codable { 


    public var planId: String?
    public var quantity: Int?

    public init(planId: String?, quantity: Int?) {
        self.planId = planId
        self.quantity = quantity
    }

    public enum CodingKeys: String, CodingKey { 
        case planId = "PlanId"
        case quantity = "Quantity"
    }

}
