//
// SaveOrganisationGroupRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Fields used to save an OrganisationGroup */
public struct SaveOrganisationGroupRequest: Codable { 


    /** The Id of the Organisation Group you want to update/save */
    public var id: Int?
    /** The updated name of the Organisation Group */
    public var organisationGroupName: String?
    /** Whether or not the Organisation Group is to be marked as deleted */
    public var isDeleted: Bool?

    public init(id: Int?, organisationGroupName: String?, isDeleted: Bool?) {
        self.id = id
        self.organisationGroupName = organisationGroupName
        self.isDeleted = isDeleted
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "Id"
        case organisationGroupName = "OrganisationGroupName"
        case isDeleted = "IsDeleted"
    }

}
