//
// SaveClientRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Fields used to save a Client */
public struct SaveClientRequest: Codable { 


    /** The Id of the Client */
    public var id: Int?
    /** The name of the Client */
    public var clientName: String?
    /** Address line 1 of the Client */
    public var clientAddressLine1: String?
    /** Address line 2 of the Client */
    public var clientAddressLine2: String?
    /** The suburb of the Client&#39;s address */
    public var clientSuburb: String?
    /** The state of the Client&#39;s address */
    public var clientState: String?
    /** The post code of the Client&#39;s address */
    public var clientPostCode: String?
    /** The name of the contact working with the Client */
    public var personOfContact: String?
    /** The phone number of the Client */
    public var clientPhoneNumber: String?
    /** The mobile phone number of the Client */
    public var clientMobileNumber: String?
    /** The email address of the Client */
    public var clientEmailAddress: String?
    /** The Client&#39;s website URL */
    public var clientWebURL: String?

    public init(id: Int?, clientName: String?, clientAddressLine1: String?, clientAddressLine2: String?, clientSuburb: String?, clientState: String?, clientPostCode: String?, personOfContact: String?, clientPhoneNumber: String?, clientMobileNumber: String?, clientEmailAddress: String?, clientWebURL: String?) {
        self.id = id
        self.clientName = clientName
        self.clientAddressLine1 = clientAddressLine1
        self.clientAddressLine2 = clientAddressLine2
        self.clientSuburb = clientSuburb
        self.clientState = clientState
        self.clientPostCode = clientPostCode
        self.personOfContact = personOfContact
        self.clientPhoneNumber = clientPhoneNumber
        self.clientMobileNumber = clientMobileNumber
        self.clientEmailAddress = clientEmailAddress
        self.clientWebURL = clientWebURL
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "Id"
        case clientName = "ClientName"
        case clientAddressLine1 = "ClientAddressLine1"
        case clientAddressLine2 = "ClientAddressLine2"
        case clientSuburb = "ClientSuburb"
        case clientState = "ClientState"
        case clientPostCode = "ClientPostCode"
        case personOfContact = "PersonOfContact"
        case clientPhoneNumber = "ClientPhoneNumber"
        case clientMobileNumber = "ClientMobileNumber"
        case clientEmailAddress = "ClientEmailAddress"
        case clientWebURL = "ClientWebURL"
    }

}
