//
// UpdateTaskRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Fields used to update a Task */
public struct UpdateTaskRequest: Codable { 


    /** The Id of the Task that is to be updated */
    public var id: Int?
    /** The updated Task Name */
    public var taskName: String?
    /** Whether or not this Task should be marked as deleted */
    public var isDeleted: Bool?
    /** Whether or not this Task should have GPS Trip Recording enabled */
    public var tripEnabled: Bool?

    public init(id: Int?, taskName: String?, isDeleted: Bool?, tripEnabled: Bool?) {
        self.id = id
        self.taskName = taskName
        self.isDeleted = isDeleted
        self.tripEnabled = tripEnabled
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "Id"
        case taskName = "TaskName"
        case isDeleted = "IsDeleted"
        case tripEnabled = "TripEnabled"
    }

}
