//
// UserProfile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UserProfile: Codable { 


    public var id: Int?
    public var organisationId: Int?
    public var userName: String?
    public var firstName: String?
    public var lastName: String?
    public var emailAddress: String?
    public var isSubscribedToNewsletter: Bool?
    public var roles: Int64?
    public var alertSettings: Int64?
    public var organisationName: String?
    public var organisationSuburb: String?
    public var organisationCountry: String?

    public init(id: Int?, organisationId: Int?, userName: String?, firstName: String?, lastName: String?, emailAddress: String?, isSubscribedToNewsletter: Bool?, roles: Int64?, alertSettings: Int64?, organisationName: String?, organisationSuburb: String?, organisationCountry: String?) {
        self.id = id
        self.organisationId = organisationId
        self.userName = userName
        self.firstName = firstName
        self.lastName = lastName
        self.emailAddress = emailAddress
        self.isSubscribedToNewsletter = isSubscribedToNewsletter
        self.roles = roles
        self.alertSettings = alertSettings
        self.organisationName = organisationName
        self.organisationSuburb = organisationSuburb
        self.organisationCountry = organisationCountry
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "Id"
        case organisationId = "OrganisationId"
        case userName = "UserName"
        case firstName = "FirstName"
        case lastName = "LastName"
        case emailAddress = "EmailAddress"
        case isSubscribedToNewsletter = "IsSubscribedToNewsletter"
        case roles = "Roles"
        case alertSettings = "AlertSettings"
        case organisationName = "OrganisationName"
        case organisationSuburb = "OrganisationSuburb"
        case organisationCountry = "OrganisationCountry"
    }

}
